version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - jonfairbanks
  versioning-strategy: increase
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.6
    - 13.1.7
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: "@material-ui/icons"
    versions:
    - 4.11.2
  - dependency-name: codemirror
    versions:
    - 5.60.0
  - dependency-name: react-codemirror2
    versions:
    - 7.2.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
